### ISSUE TITLE
Support for API keys

### ISSUE THREAD

**Issue by leegarrett** [inwx/ansible-collection#17]
Currently, inwx.collection.dns requires the username and password and a deactivated 2FA to work. These credentials are however also used to:

1. Buy/sell/cancel/transfer new domains
2. View previous invoices
3. View invoice addresses
4. (de)activate DNSSEC
5. Transfer money from the account
6. Buy/renew TLS certificates
7. Enable 2FA to lock out the original user from the account
8. ... and many more things

Those are all things I'd usually not want to do with the inwx.collection.dns ansible module.

The solution is support API keys, just like they are supported by other companies offering similar solutions. The workflow would be:

- Generate an API key in the inwx.de webfrontend
- Set fine-grained permissions to what the API key can and cannot do
- Add the API key to the ansible-vault to be used there
- Use the API key non-interactively for the use case

**Comment by schlamar** [comment]
I was in contact with INWX support about this topic. API keys are planned, however there is no ETA yet.

An alternative solution right now is that they can provide you an additional restrictive account with a custom set of permissions.

**Comment by yomofo2s** [comment]
Same issue here. I hope Inwx can provide API keys soonest!

**Comment by leegarrett** [comment]
Hi, is there an update on when this might be implemented?

**Comment by inwx-developer** [comment]
Currently it's not planned for the near future because we have a good workaround already.

When you login to your INWX account, go to "User Management" and create a new user which you only use for API access. This user can have 2FA disabled and you can also define different permissions.

**Comment by leegarrett** [comment]
> Currently it's not planned for the near future because we have a good workaround already.
> 
> When you login to your INWX account, go to "User Management" and create a new user which you only use for API access. This user can have 2FA disabled and you can also define different permissions.

Nice, I didn't know this exists. This is what I was looking for.

**Comment by inwx-developer** [comment]
Additional users can be created and managed in the "User Management" area, therefore the issue is closed.

**Comment by pkoevesdi** [comment]
I'd like to bring this up again. It's totally annoying, that the new user has to have a first AND last name, an Email address, phone number and a postal address. This doesn't make sense for a machine, which an API user typically is.
Also, the available permissions are far too broad. I'd need only a permission to set a certain DNS record type. Just enough to perform an DNS challenge via API.
So, to me, this is not closed at all, sorry.

**Comment by pkoevesdi** [comment]
Also, 2fa seems not supported for this aux user, although projects like acme.sh can handle 2fa with inwx.

**Comment by ddmler** [comment]
We created a ticket internally to add api keys.

**Comment by pkoevesdi** [comment]
Thanks. 
I consider the way OVH does it, quite exemplary:
![Grafik](https://docs.certifytheweb.com/assets/ovh-api-keys-creation-form.png)
But, please add optional 2FA for the API keys too.

Is there some proposed release date already? Can this ticket be reopened again?

**Comment by enaut** [comment]
I was looking for this functionality too... it is rather standard I think!

**Comment by Gorkrul** [comment]
me was looking for this API key function, too... in january 2025

any ETA?
