### ISSUE TITLE
add inwx to the official ansible-modules

### ISSUE THREAD

**Issue by n0emis** [inwx/ansible-collection#2]
To make it easier to use and find this module, it would be handy, if it was included in the official repository like [cloudflare does](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/net_tools/cloudflare_dns.py).

**Comment by NickUfer** [comment]
Hey, we already opened a merge request once, but it seems that no new modules are added anymore. https://github.com/ansible/ansible/pull/64426 . Someone in the comments pointed us to the new feature of ansible collections which will may be the new way of adding modules.
