### ISSUE TITLE
Galaxy URL in README is no longer optimal

### ISSUE THREAD

**Issue by felixfontein** [inwx/ansible-collection#21]
Due to the Ansible Galaxy codebase change, https://galaxy.ansible.com/inwx/collection now points to a 404 page which contains search results (with the inwx.collection URL). Better change the URL in the README to https://galaxy.ansible.com/ui/repo/published/inwx/collection/.

Ref: https://github.com/ansible-collections/news-for-maintainers/issues/59

**Comment by ddmler** [comment]
Thanks for letting us know! I fixed the link.
