### ISSUE TITLE
Using the module causes systemd WALL messages

### ISSUE THREAD

**Issue by dragetd** [inwx/ansible-collection#8]
I have a very strange behavior. Every time the module is run, Ansible/python3 uses SystemD to print out the message as a WALL message, i.e. it gets printed into every console of every logged in user.

It is probably some Ansible mechanism, but I am unable to find anything on the internet that describes this behavior. Maybe anyone else is experiencing this and can tell me, why it happens?

If not, I will close this issue again.

```
Broadcast message from systemd-journald@evo (Wed 2021-05-12 22:10:14 CEST):

python3[3172258]: ansible-inwx.collection.dns Invoked with domain=x.de type=MX record= state=present priority=0 value=x.uberspace.de ttl=900 username=x password=NOT_LOGGING_PARAMETER api_env=live solo=False weight=1 algorithm=None flag=None tag=None cert_usage=None hash_type=None regex=None port=None selector=None service=None substitution=None
```

**Comment by NickUfer** [comment]
Hmm, that is very strange... seems to me like some debugging. [Here](https://github.com/ansible/ansible/issues/29506#issuecomment-328517080) someone used `ANSIBLE_DEBUG=1` to get similar outputs
